### PR TITLE
Fix the reported error and other possibles

### PR DESCRIPTION
**Pull request by bouwew**

### CODE REVIEW

**Comment by CoMPaTech** [comment]
This won't work, as the call to `get_point_log_id` would fail already. So we either need to change that function or decide not to call it based upon other logic.

**Comment by CoMPaTech** [comment]
I'll try to come up with something later this afternoon

**Comment by CoMPaTech** [comment]
Wrong usage of tab and space, didn't mean to close it

**Comment by bouwew** [comment]
I see what you mean, I'll try something else.

**Pull request closed without merging**
