### PR TITLE
Fix (not) getting last_active_schema for legacy anna

### PR DESCRIPTION
**Pull request by bouwew**
I forgot to disable this function for legacy anna, causing issues as reported at various places.

### CODE REVIEW

**Comment by bouwew** [comment]
@CoMPaTech 

Tested and confirmed fixing the bug reported by 1 legacy Anna user.

When checked OK, please upload to pypi so I can get this into HAC.

**Comment by CoMPaTech** [comment]
Working on it :)

**Comment by CoMPaTech** [comment]
Code looks fine to me, works as well on my (though minimal) setup (non-legacy and only used for switching valve), merging.

**Comment by CoMPaTech** [comment]
Pushed https://pypi.org/project/haanna/

**Comment by bouwew** [comment]
Super, thanks!

**Pull request merged**
