### PR TITLE
Minor improvements and corrections, and black implemented

### PR DESCRIPTION
**Pull request by bouwew**
Code should now be ready for integration in HA.

### CODE REVIEW

**Comment by CoMPaTech** [comment]
I'll have a test tonight (if everything lines up)!

**Comment by bouwew** [comment]
Yes, please, in combi with the updated anna-ha-code :)

When you find all to be OK and haanna 0.11.1 is released on Pypi, I will create a pull-request for the updated plugwise-code in the HA-repository.

**Comment by CoMPaTech** [comment]
Looks good to me, I'll merge and have a go at uploading it to PyPi

**Comment by CoMPaTech** [comment]
0.11.1 has been pushed as well

**Pull request merged**
